<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net48;net8.0;net9.0;net10.0</TargetFrameworks>
	<LangVersion>10.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>QuestPDF.HTML</Title>
    <Company>Maple Reinders</Company>
    <Authors>Maple Reinders</Authors>
    <Description>
        QuestPDF.HTML is an extension for QuestPDF that allows to generate PDF from HTML. 
        Originally created by Relorer (https://github.com/Relorer/HTMLToQPDF).
    </Description>
    <PackageProjectUrl>https://github.com/Maple-Reinders/QuestPDF.HTML</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageId>Maple.QuestPDF.HTML</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Maple-Reinders/QuestPDF.HTML</RepositoryUrl>
    <PackageTags>pdf, file, export, generate, generation, tool, create, creation, render, document, format, quest, html, library, converter, open, source, free, standard, core</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <AssemblyVersion>1.6.0</AssemblyVersion>
    <FileVersion>1.6.0</FileVersion>
    <Version>1.6.0</Version>
    <PackageReleaseNotes>
v1.6.0:
- improve table rendering for complex and nested structures
- refine table parsing for accurate row identification
- fix some pages not rendering


    </PackageReleaseNotes>
  </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
	  <Reference Include="System.Net.Http" />
	  <Reference Include="System.Web" />
    </ItemGroup>

	<ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="QuestPDF" Version="2025.12.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
